services:
  app:
    build:
      context: .
      target: dev
    container_name: laravel_app
    working_dir: /var/www
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - .:/var/www
    env_file:
      - .env
    command: composer run dev
    ports:
      - "8001:8000"
      - "5173:5173"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
