services:
  app:
    build:
      context: .
      target: dev
    container_name: system_app
    working_dir: /var/www
    user: "1000:1000"
    restart: always
    environment:
      HOME: /home/app
      COMPOSER_HOME: /home/app/.composer
      npm_config_cache: /home/app/.npm
    volumes:
      - .:/var/www
      - vendor_data:/var/www/vendor
      - node_modules_data:/var/www/node_modules
      - composer_cache:/home/app/.composer/cache
      - npm_cache:/home/app/.npm
    env_file:
      - .env
    command: >
      sh -c "
      composer install --no-interaction --prefer-dist &&
      npm install &&
      composer run dev
      "
    ports:
      - "8002:8000"
      - "5173:5173"
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: system_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: system_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data:
  vendor_data:
  node_modules_data:
  composer_cache:
  npm_cache:
