import {
  Home,
  Bell,
  NotebookPen,
  UserPlus,
  Layers,
  BookOpen,
  Users,
  Building2,
  Globe,
  Clock,
  CalendarClock,
  CalendarDays,
  ShieldCheck,
  Lock,
  UserCircle,
  LayoutDashboard,
  SlidersHorizontal,
  Bot,
  BadgeCheck,
  MapPin,
  ClipboardCheck,
  UserX,
  History,
} from "@lucide/vue";

// Maps a menu item's `icon` string to its Lucide component.
export const menuIcons = {
  home: Home,
  notification: Bell,
  "notebook-pen": NotebookPen,
  "user-plus": UserPlus,
  classes: Layers,
  course: BookOpen,
  user: Users,
  building_management: Building2,
  website: Globe,
  shift: Clock,
  schedule: CalendarClock,
  official_leave: CalendarDays,
  account_security: ShieldCheck,
  login_security: Lock,
  profile: UserCircle,
  "enroll-config": SlidersHorizontal,
  attendance_settings: Bot,
  certificate: BadgeCheck,
  access_locations: MapPin,
  pre_attendance: ClipboardCheck,
  absence_block: UserX,
  class_history: History,
};

// Used when an item's `icon` key has no entry above.
export const defaultMenuIcon = LayoutDashboard;
