<script setup>
import { Head, useForm, usePage } from '@inertiajs/vue3'
import { Breadcrumbs } from '../../../components/ui/breadcrumbs'
import { PageHero } from '../../../components/ui/page-hero'
import DashboardLayout from '../../../layouts/DashboardLayout.vue'
import UserAccountForm from './components/UserAccountForm.vue'
const page = usePage(), user = page.props.user, roleOptions = page.props.roleOptions ?? [], s = user.student_data ?? {}, i = user.instructor_data ?? {}
const form = useForm({ name: user.name ?? '', email: user.email ?? '', password: '', password_confirmation: '', role: user.role ?? 'admin', account_status: Boolean(user.status), avatar: null, student_code: s.student_code ?? '', student_full_name: s.full_name ?? '', student_first_name: s.first_name ?? '', student_last_name: s.last_name ?? '', student_full_name_kh: s.full_name_kh ?? '', student_gender: s.gender ?? '', student_date_of_birth: s.date_of_birth ?? '', student_phone: s.phone ?? '', student_email: s.email ?? '', student_class_id: s.class_id ?? '', parent_name: s.parent_name ?? '', parent_phone: s.parent_phone ?? '', student_address: s.address ?? '', student_status: s.status ?? true, instructor_code: i.instructor_code ?? '', instructor_full_name: i.full_name ?? '', instructor_first_name: i.first_name ?? '', instructor_last_name: i.last_name ?? '', instructor_full_name_kh: i.full_name_kh ?? '', instructor_gender: i.gender ?? '', instructor_date_of_birth: i.date_of_birth ?? '', instructor_phone: i.phone ?? '', instructor_email: i.email ?? '', specialization: i.specialization ?? '', employment_type: i.employment_type ?? 'full_time', shift_preference: i.shift_preference ?? 'morning_evening', available_for_class: i.available_for_class ?? true, hire_date: i.hire_date ?? '', instructor_address: i.address ?? '', instructor_status: i.status ?? true })
</script>
<template><Head title="Edit User" /><DashboardLayout><section class="space-y-6"><Breadcrumbs :items="[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Users', href: '/dashboard/users' }, { label: 'Edit', current: true }]" /><PageHero eyebrow="User Management" title="Edit User" description="Update the login account and role-specific profile." /><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><UserAccountForm :form="form" :role-options="roleOptions" :edit="true" submit-label="Save Changes" @submit="form.put(`/dashboard/users/${user.id}`)" /></div></section></DashboardLayout></template>
